[package]
name = "mirror-clone"
version = "0.1.0"
authors = ["Alex Chi <iskyzh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
reqwest = { version = "0.10", features = ["rustls-tls", "stream"] }
overlay = { path = "./overlay" }
log = "0.4"
futures-util = "0.3"
flate2 = "1.0"
tar = "0.4"
bytes = "0.6"
regex = "1"
indicatif = "0.15"
futures = "0.3"
futures-retry = "0.5"
thiserror = "1.0"
rand = "0.7"
slog-term = "2.6"
slog = "2.5"
slog-async = "2.5"
slog-scope-futures = "0.1"
slog-scope = "4.3"
md-5 = "0.9"
sha-1 = "0.9"
sha2 = "0.9"
itertools = "0.9"
serde_json = "1.0"
clap = "2.33"
walkdir = "2.3"
serde = { version = "1.0", features = ["derive"] }
opam_file_format = { git = "https://github.com/PhotonQuantum/opam-file-format-rs", branch = "main" }

[workspace]
members = [
    "overlay"
]
